version: "3.2"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment: 
    #   - ENVS=

  mariadb:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: this_is_a_password_for_testing_only
      MARIADB_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  zipkin-mysql:
    image: ghcr.io/openzipkin/zipkin-mysql:${TAG:-latest}

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      - MYSQL_HOST=zipkin-mysql
      # Uncomment to enable self-tracing
      - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUGversion: "3.2"

volumes:
  mariadb-data: