name: reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies with pnpm
        run: pnpm install

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "{src,apps,libs,test}/**/*.ts"

          
